### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by DaveOrpen** [joostej/pangea-rally-app#1]
I wonder if this is a better alternative to using Trello? Keep all issues and docs versioned together

**Comment by joostej** [comment]
Perhaps. However, I like the idea of using a well known tool like Trello - given that experience with both GitHub and Trello could be beneficial for the testers.

**Comment by DaveOrpen** [comment]
I agree :D Let's let them experience the hell that is the real world of keeping multiple tools used on a project in sync...
